import { MigrationInterface, QueryRunner } from "typeorm";

export class Baseline1786690949350 implements MigrationInterface {
    name = 'Baseline1786690949350'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."tenants_status_enum" AS ENUM('trial', 'active', 'suspended', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."tenants_plan_enum" AS ENUM('start', 'professional', 'enterprise')`);
        await queryRunner.query(`CREATE TABLE "tenants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(200) NOT NULL, "subdomain" character varying(63) NOT NULL, "baseCurrency" character varying(3) NOT NULL DEFAULT 'UZS', "status" "public"."tenants_status_enum" NOT NULL DEFAULT 'trial', "plan" "public"."tenants_plan_enum" NOT NULL DEFAULT 'start', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_21bb89e012fa5b58532009c1601" UNIQUE ("subdomain"), CONSTRAINT "PK_53be67a04681c66b87ee27c9321" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "properties" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "name" character varying(200) NOT NULL, "address" character varying(500), "currency" character varying(3) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2d83bfa0b9fcd45dee1785af44d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6bcd5c3d46689610c9bbf14e0e" ON "properties"  ("tenant_id") `);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'invited', 'disabled')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid, "email" character varying(255) NOT NULL, "password_hash" character varying(255) NOT NULL, "full_name" character varying(200) NOT NULL, "status" "public"."users_status_enum" NOT NULL DEFAULT 'active', "is_platform_admin" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e9f4c2efab52114c4e99e28efb1" UNIQUE ("tenant_id", "email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_109638590074998bb72a2f2cf0" ON "users"  ("tenant_id") `);
        await queryRunner.query(`CREATE TYPE "public"."permissions_module_enum" AS ENUM('booking', 'front_desk', 'housekeeping', 'warehouse', 'pos', 'guest_crm', 'invoicing', 'accounting', 'reports', 'billing', 'users_roles', 'tenant_settings')`);
        await queryRunner.query(`CREATE TYPE "public"."permissions_action_enum" AS ENUM('view', 'create', 'edit', 'delete', 'approve')`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "module" "public"."permissions_module_enum" NOT NULL, "action" "public"."permissions_action_enum" NOT NULL, "description" character varying(200), CONSTRAINT "UQ_35ddf0f00aaedd9b4bd19f1f49b" UNIQUE ("module", "action"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid, "name" character varying(100) NOT NULL, "system_key" character varying(50), "is_system" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e59a01f4fe46ebbece575d9a0f" ON "roles"  ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "user_id" uuid NOT NULL, "role_id" uuid NOT NULL, "property_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8acd5cf26ebd158416f477de799" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_156cd3e5710ec8c0a4bbe7865f" ON "user_roles"  ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_87b8888186ca9769c960e92687" ON "user_roles"  ("user_id") `);
        await queryRunner.query(`CREATE TABLE "guests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "full_name" character varying(200) NOT NULL, "phone" character varying(30), "email" character varying(255), "nationality" character varying(100), "document_type" character varying(30), "document_number" character varying(50), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4948267e93869ddcc6b340a2c46" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1e3617f419dde1dd070850e27d" ON "guests"  ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "room_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "property_id" uuid NOT NULL, "name" character varying(100) NOT NULL, "base_price" numeric(12,2) NOT NULL, "max_occupancy" integer NOT NULL DEFAULT '2', "description" character varying(1000), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b6e1d0a9b67d4b9fbff9c35ab69" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_410c0fdcad7e40c3d8f9ce6014" ON "room_types"  ("tenant_id", "property_id") `);
        await queryRunner.query(`CREATE TYPE "public"."rooms_status_enum" AS ENUM('available', 'occupied', 'maintenance', 'out_of_order')`);
        await queryRunner.query(`CREATE TYPE "public"."rooms_housekeeping_status_enum" AS ENUM('clean', 'dirty', 'in_progress', 'inspected')`);
        await queryRunner.query(`CREATE TABLE "rooms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "property_id" uuid NOT NULL, "room_type_id" uuid NOT NULL, "room_number" character varying(20) NOT NULL, "floor" integer, "status" "public"."rooms_status_enum" NOT NULL DEFAULT 'available', "housekeeping_status" "public"."rooms_housekeeping_status_enum" NOT NULL DEFAULT 'clean', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_856e24445b9e0b7e35bf1e6390a" UNIQUE ("property_id", "room_number"), CONSTRAINT "PK_0368a2d7c215f2d0458a54933f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e9c1c648697923440a802d0407" ON "rooms"  ("tenant_id", "property_id") `);
        await queryRunner.query(`CREATE TYPE "public"."bookings_status_enum" AS ENUM('pending', 'confirmed', 'checked_in', 'checked_out', 'cancelled', 'no_show')`);
        await queryRunner.query(`CREATE TYPE "public"."bookings_source_enum" AS ENUM('direct', 'website', 'ota', 'exely')`);
        await queryRunner.query(`CREATE TABLE "bookings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "property_id" uuid NOT NULL, "room_id" uuid NOT NULL, "guest_id" uuid NOT NULL, "check_in" date NOT NULL, "check_out" date NOT NULL, "status" "public"."bookings_status_enum" NOT NULL DEFAULT 'confirmed', "source" "public"."bookings_source_enum" NOT NULL DEFAULT 'direct', "total_amount" numeric(12,2) NOT NULL, "currency" character varying(3) NOT NULL, "external_ref" character varying(100), "notes" character varying(1000), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bee6805982cc1e248e94ce94957" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5ad78cbd837f006dec91f3612e" ON "bookings"  ("room_id", "check_in", "check_out") `);
        await queryRunner.query(`CREATE INDEX "IDX_63da07267a99371403a2fec905" ON "bookings"  ("tenant_id", "property_id") `);
        await queryRunner.query(`CREATE TABLE "warehouses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "property_id" uuid NOT NULL, "name" character varying(150) NOT NULL, "is_default" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_56ae21ee2432b2270b48867e4be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ad7eba9fd8ca8681f5eac144da" ON "warehouses"  ("tenant_id", "property_id") `);
        await queryRunner.query(`CREATE TABLE "suppliers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "name" character varying(200) NOT NULL, "contact_person" character varying(150), "phone" character varying(30), "email" character varying(255), "address" character varying(500), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b70ac51766a9e3144f778cfe81e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b0d0350059126fa08fddc3c7a4" ON "suppliers"  ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "stock_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "sku" character varying(50) NOT NULL, "name" character varying(200) NOT NULL, "unit" character varying(20) NOT NULL, "category" character varying(100), "reorder_point" numeric(12,3) NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_61a60265db224bb276a36c16fc0" UNIQUE ("tenant_id", "sku"), CONSTRAINT "PK_52a266aa3e04b8ad1f01088f3f0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_598273c2e92c500b453fc8c4ae" ON "stock_items"  ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "stock_lots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "warehouse_id" uuid NOT NULL, "stock_item_id" uuid NOT NULL, "purchase_order_id" uuid, "quantity_received" numeric(14,3) NOT NULL, "quantity_remaining" numeric(14,3) NOT NULL, "unit_cost" numeric(14,4) NOT NULL, "received_at" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_578c4d59145e7d590780f29347b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bcb14df718a5171765e9a4ca9c" ON "stock_lots"  ("tenant_id", "warehouse_id", "stock_item_id", "received_at") `);
        await queryRunner.query(`CREATE TYPE "public"."stock_transactions_type_enum" AS ENUM('receipt', 'issue', 'adjustment')`);
        await queryRunner.query(`CREATE TABLE "stock_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "warehouse_id" uuid NOT NULL, "stock_item_id" uuid NOT NULL, "type" "public"."stock_transactions_type_enum" NOT NULL, "quantity" numeric(14,3) NOT NULL, "unit_cost" numeric(14,4) NOT NULL, "total_cost" numeric(14,2) NOT NULL, "reference_type" character varying(50), "reference_id" uuid, "notes" character varying(500), "created_by_user_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1aa2430f5ac950c26da6e1ff222" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1b4b5c061c24b38f8b4667e9a3" ON "stock_transactions"  ("tenant_id", "warehouse_id", "stock_item_id") `);
        await queryRunner.query(`CREATE TABLE "purchase_order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "purchase_order_id" uuid NOT NULL, "stock_item_id" uuid NOT NULL, "quantity_ordered" numeric(14,3) NOT NULL, "quantity_received" numeric(14,3) NOT NULL DEFAULT '0', "unit_cost" numeric(14,4) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e8b7568d25c41e3290db596b312" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_orders_status_enum" AS ENUM('draft', 'pending_approval', 'approved', 'rejected', 'partially_received', 'received', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "purchase_orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "property_id" uuid NOT NULL, "warehouse_id" uuid NOT NULL, "supplier_id" uuid NOT NULL, "status" "public"."purchase_orders_status_enum" NOT NULL DEFAULT 'pending_approval', "total_amount" numeric(14,2) NOT NULL DEFAULT '0', "currency" character varying(3) NOT NULL DEFAULT 'UZS', "created_by_user_id" uuid NOT NULL, "approved_by_user_id" uuid, "approved_at" TIMESTAMP, "notes" character varying(1000), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_05148947415204a897e8beb2553" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_179894a85edbd6b6e584bf62a4" ON "purchase_orders"  ("tenant_id", "property_id") `);
        await queryRunner.query(`CREATE TABLE "pos_outlets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "property_id" uuid NOT NULL, "name" character varying(150) NOT NULL, "is_default" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ebd3f666dc429c6b72240455fc5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_abb1b6e44ec2d76d3a65b3e9ea" ON "pos_outlets"  ("tenant_id", "property_id") `);
        await queryRunner.query(`CREATE TABLE "menu_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "name" character varying(200) NOT NULL, "category" character varying(100), "price" numeric(12,2) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_57e6188f929e5dc6919168620c8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_30c325b9c870a0353c95dc064f" ON "menu_items"  ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "pos_order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "menu_item_id" uuid NOT NULL, "quantity" integer NOT NULL, "unit_price" numeric(12,2) NOT NULL, "notes" character varying(300), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ad5bd3899fd281de4614a89f629" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."pos_orders_status_enum" AS ENUM('open', 'paid', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."pos_orders_payment_method_enum" AS ENUM('cash', 'card', 'room_account')`);
        await queryRunner.query(`CREATE TABLE "pos_orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "property_id" uuid NOT NULL, "outlet_id" uuid NOT NULL, "status" "public"."pos_orders_status_enum" NOT NULL DEFAULT 'open', "table_number" character varying(20), "guest_id" uuid, "booking_id" uuid, "payment_method" "public"."pos_orders_payment_method_enum", "total_amount" numeric(12,2) NOT NULL DEFAULT '0', "currency" character varying(3) NOT NULL DEFAULT 'UZS', "created_by_user_id" uuid NOT NULL, "paid_at" TIMESTAMP, "notes" character varying(500), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fe63b2bc474b2dc257089d09485" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bca276153ee97481b90af8aabb" ON "pos_orders"  ("tenant_id", "property_id") `);
        await queryRunner.query(`CREATE TYPE "public"."housekeeping_tasks_status_enum" AS ENUM('pending', 'in_progress', 'done', 'inspected', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "housekeeping_tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "property_id" uuid NOT NULL, "room_id" uuid NOT NULL, "status" "public"."housekeeping_tasks_status_enum" NOT NULL DEFAULT 'pending', "assigned_to_user_id" uuid, "notes" character varying(500), "started_at" TIMESTAMP, "completed_at" TIMESTAMP, "inspected_at" TIMESTAMP, "inspected_by_user_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8ff7ba6f00d5b405e194a3a55ac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a2f95679b38ca1788cfa999a64" ON "housekeeping_tasks"  ("tenant_id", "property_id") `);
        await queryRunner.query(`CREATE TYPE "public"."invoice_lines_source_enum" AS ENUM('room_charge', 'pos_order', 'manual', 'adjustment')`);
        await queryRunner.query(`CREATE TABLE "invoice_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoice_id" uuid NOT NULL, "description" character varying(255) NOT NULL, "source" "public"."invoice_lines_source_enum" NOT NULL DEFAULT 'manual', "source_id" uuid, "quantity" numeric(12,2) NOT NULL DEFAULT '1', "unit_price" numeric(12,2) NOT NULL, "amount" numeric(12,2) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3d18eb48142b916f581f0c21a65" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."invoice_payments_method_enum" AS ENUM('cash', 'card', 'bank_transfer')`);
        await queryRunner.query(`CREATE TABLE "invoice_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoice_id" uuid NOT NULL, "amount" numeric(12,2) NOT NULL, "method" "public"."invoice_payments_method_enum" NOT NULL, "received_by_user_id" uuid NOT NULL, "notes" character varying(500), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e19c9ebfa432289f510de7b4e99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('open', 'issued', 'paid', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "property_id" uuid NOT NULL, "booking_id" uuid NOT NULL, "guest_id" uuid NOT NULL, "status" "public"."invoices_status_enum" NOT NULL DEFAULT 'open', "total_amount" numeric(12,2) NOT NULL DEFAULT '0', "paid_amount" numeric(12,2) NOT NULL DEFAULT '0', "currency" character varying(3) NOT NULL DEFAULT 'UZS', "issued_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ed9c7aa7846704bbcb648377e8f" UNIQUE ("booking_id"), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d45cd20e42bc8a7c50e80af8cd" ON "invoices"  ("tenant_id", "property_id") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions"  ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions"  ("permission_id") `);
        await queryRunner.query(`ALTER TABLE "properties" ADD CONSTRAINT "FK_6bcd5c3d46689610c9bbf14e0eb" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_109638590074998bb72a2f2cf08" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "FK_e59a01f4fe46ebbece575d9a0fc" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_22b4348eca914f216201aae2fd1" FOREIGN KEY ("property_id") REFERENCES "properties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guests" ADD CONSTRAINT "FK_1e3617f419dde1dd070850e27d2" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_types" ADD CONSTRAINT "FK_256643d841e9459e650f110ae1e" FOREIGN KEY ("property_id") REFERENCES "properties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD CONSTRAINT "FK_f3a3e21cdec3d9f8069edf6f52f" FOREIGN KEY ("property_id") REFERENCES "properties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD CONSTRAINT "FK_8a380bdc519b8701daf0ec62da0" FOREIGN KEY ("room_type_id") REFERENCES "room_types"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_afa260d0e51f81520a480817702" FOREIGN KEY ("property_id") REFERENCES "properties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_0b0fc32fe6bd0119e281628df7a" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_b4403309538387262d97fdf2462" FOREIGN KEY ("guest_id") REFERENCES "guests"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD CONSTRAINT "FK_3f92bb44026cedfe235c8b91244" FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD CONSTRAINT "FK_b61e92129bc6d684b4c3a4c4c93" FOREIGN KEY ("stock_item_id") REFERENCES "stock_items"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pos_order_items" ADD CONSTRAINT "FK_e36f2aace55b70811dbaa69f9f4" FOREIGN KEY ("order_id") REFERENCES "pos_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pos_order_items" ADD CONSTRAINT "FK_a18075b5f4396ec6f7bf8969155" FOREIGN KEY ("menu_item_id") REFERENCES "menu_items"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "housekeeping_tasks" ADD CONSTRAINT "FK_74d1760b59de0efd350709de99c" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" ADD CONSTRAINT "FK_2da95dc86a54a00ff20ce46d0fe" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_payments" ADD CONSTRAINT "FK_e94fa427d3da279450dba6f4aa6" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_ed9c7aa7846704bbcb648377e8f" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_1916919510894fecce51c74ede1" FOREIGN KEY ("guest_id") REFERENCES "guests"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_1916919510894fecce51c74ede1"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_ed9c7aa7846704bbcb648377e8f"`);
        await queryRunner.query(`ALTER TABLE "invoice_payments" DROP CONSTRAINT "FK_e94fa427d3da279450dba6f4aa6"`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" DROP CONSTRAINT "FK_2da95dc86a54a00ff20ce46d0fe"`);
        await queryRunner.query(`ALTER TABLE "housekeeping_tasks" DROP CONSTRAINT "FK_74d1760b59de0efd350709de99c"`);
        await queryRunner.query(`ALTER TABLE "pos_order_items" DROP CONSTRAINT "FK_a18075b5f4396ec6f7bf8969155"`);
        await queryRunner.query(`ALTER TABLE "pos_order_items" DROP CONSTRAINT "FK_e36f2aace55b70811dbaa69f9f4"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP CONSTRAINT "FK_b61e92129bc6d684b4c3a4c4c93"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP CONSTRAINT "FK_3f92bb44026cedfe235c8b91244"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_b4403309538387262d97fdf2462"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_0b0fc32fe6bd0119e281628df7a"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_afa260d0e51f81520a480817702"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP CONSTRAINT "FK_8a380bdc519b8701daf0ec62da0"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP CONSTRAINT "FK_f3a3e21cdec3d9f8069edf6f52f"`);
        await queryRunner.query(`ALTER TABLE "room_types" DROP CONSTRAINT "FK_256643d841e9459e650f110ae1e"`);
        await queryRunner.query(`ALTER TABLE "guests" DROP CONSTRAINT "FK_1e3617f419dde1dd070850e27d2"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_22b4348eca914f216201aae2fd1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "FK_e59a01f4fe46ebbece575d9a0fc"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_109638590074998bb72a2f2cf08"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP CONSTRAINT "FK_6bcd5c3d46689610c9bbf14e0eb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d45cd20e42bc8a7c50e80af8cd"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`DROP TABLE "invoice_payments"`);
        await queryRunner.query(`DROP TYPE "public"."invoice_payments_method_enum"`);
        await queryRunner.query(`DROP TABLE "invoice_lines"`);
        await queryRunner.query(`DROP TYPE "public"."invoice_lines_source_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a2f95679b38ca1788cfa999a64"`);
        await queryRunner.query(`DROP TABLE "housekeeping_tasks"`);
        await queryRunner.query(`DROP TYPE "public"."housekeeping_tasks_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bca276153ee97481b90af8aabb"`);
        await queryRunner.query(`DROP TABLE "pos_orders"`);
        await queryRunner.query(`DROP TYPE "public"."pos_orders_payment_method_enum"`);
        await queryRunner.query(`DROP TYPE "public"."pos_orders_status_enum"`);
        await queryRunner.query(`DROP TABLE "pos_order_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_30c325b9c870a0353c95dc064f"`);
        await queryRunner.query(`DROP TABLE "menu_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_abb1b6e44ec2d76d3a65b3e9ea"`);
        await queryRunner.query(`DROP TABLE "pos_outlets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_179894a85edbd6b6e584bf62a4"`);
        await queryRunner.query(`DROP TABLE "purchase_orders"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_orders_status_enum"`);
        await queryRunner.query(`DROP TABLE "purchase_order_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1b4b5c061c24b38f8b4667e9a3"`);
        await queryRunner.query(`DROP TABLE "stock_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."stock_transactions_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bcb14df718a5171765e9a4ca9c"`);
        await queryRunner.query(`DROP TABLE "stock_lots"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_598273c2e92c500b453fc8c4ae"`);
        await queryRunner.query(`DROP TABLE "stock_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b0d0350059126fa08fddc3c7a4"`);
        await queryRunner.query(`DROP TABLE "suppliers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad7eba9fd8ca8681f5eac144da"`);
        await queryRunner.query(`DROP TABLE "warehouses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_63da07267a99371403a2fec905"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5ad78cbd837f006dec91f3612e"`);
        await queryRunner.query(`DROP TABLE "bookings"`);
        await queryRunner.query(`DROP TYPE "public"."bookings_source_enum"`);
        await queryRunner.query(`DROP TYPE "public"."bookings_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9c1c648697923440a802d0407"`);
        await queryRunner.query(`DROP TABLE "rooms"`);
        await queryRunner.query(`DROP TYPE "public"."rooms_housekeeping_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."rooms_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_410c0fdcad7e40c3d8f9ce6014"`);
        await queryRunner.query(`DROP TABLE "room_types"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1e3617f419dde1dd070850e27d"`);
        await queryRunner.query(`DROP TABLE "guests"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87b8888186ca9769c960e92687"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_156cd3e5710ec8c0a4bbe7865f"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e59a01f4fe46ebbece575d9a0f"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TYPE "public"."permissions_action_enum"`);
        await queryRunner.query(`DROP TYPE "public"."permissions_module_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_109638590074998bb72a2f2cf0"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6bcd5c3d46689610c9bbf14e0e"`);
        await queryRunner.query(`DROP TABLE "properties"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
        await queryRunner.query(`DROP TYPE "public"."tenants_plan_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tenants_status_enum"`);
    }

}
