import { AccountDepartment, AccountType, NormalBalance } from '../entities/account.entity';

export interface DefaultAccountDefinition {
  code: string;
  name: string;
  type: AccountType;
  department: AccountDepartment | null;
  normalBalance: NormalBalance;
  systemKey: string | null;
}

// USALI (Uniform System of Accounts for the Lodging Industry, 12th Revised Edition,
// HFTP/STR/CoStar, 2024) rasmiy nashri asosidagi TO'LIQ hisoblar rejasi — har bir
// yangi tenant ro'yxatdan o'tishda avtomatik yaratiladi (qarang: TenantsService).
//
// Manba: rasmiy 12th Edition "Part I - Operating Statements" va "Part VI - Revenue
// and Expense Guide" jadvallari (Schedule 1 Rooms, Schedule 2 Food and Beverage,
// Schedule 4 Miscellaneous Income, Schedule 5 Administrative and General, Schedule 6
// Information and Telecommunications Systems, Schedule 7 Sales and Marketing,
// Schedule 8 Property Operation and Maintenance, Schedule 9 Energy Water and Waste,
// Schedule 10 Management Fees, Schedule 11 Nonoperating Income and Expenses,
// Schedule 14 Payroll-Related Expenses).
//
// Qamrovdan ATAYLAB chiqarilgan/soddalashtirilgan qismlar (foydalanuvchi bilan
// kelishilgan qaror, MVP bosqichida operatsion modul yo'qligi sababli):
//  - Schedule 3 (Other Operated Departments — Golf/Health Club-Spa/Parking va h.k.):
//    faqat bitta umumiy "Other Operated Revenue/Expense" hisobi bilan cheklangan;
//    tegishli modul (Golf/Spa) qo'shilganda kengaytiriladi.
//  - Schedule 1-1 (Executive Lounge) va Schedule 12-13 (House Laundry, Staff Dining):
//    kiritilmagan — bular allocation/net-recovery mexanizmiga asoslangan, niche
//    schedule'lar (faqat ayrim mehmonxonalarda ishlaydi).
//  - Schedule 6 "System Expenses" (IT xarajatlarini har bir departamentga taqsimlash):
//    bitta umumiy hisobga soddalashtirilgan.
//  - Compensation (ish haqi): rol bo'yicha ajratilgan (masalan Front Office,
//    Housekeeping), lekin Management/Nonmanagement darajasiga BO'LINMAGAN — tizimda
//    hali payroll moduli yo'qligi sababli bu farq avtomatlashtirilmaydi va amalda
//    foyda keltirmaydi.
//  - Payroll-Related Expenses (Schedule 14) tafsiloti HAR BIR DEPARTAMENT uchun
//    TAKRORLANMAGAN — rasmiy manbaning o'zida ham bu alohida, umumiy (property-wide)
//    schedule sifatida beriladi: har bir departament schedule'i faqat bitta
//    "Payroll-Related Expenses" jamlama qatorini ko'rsatadi, tafsilot esa Schedule 14
//    orqali property darajasida yuritiladi (haqiqiy hotel buxgalteriyasida ham
//    ish haqi tarkibi departamentlar bo'yicha emas, balki turi bo'yicha kuzatiladi).
//
// \`systemKey\` berilgan hisoblar AccountingService tomonidan avtomatik provodka
// (auto-posting) uchun ishlatiladi — bu qiymatlar KOD EMAS, shuning uchun tenant
// hisob nomini/kodini keyinchalik o'zgartirsa ham avtomatik provodka ishlashda davom etadi.
export const DEFAULT_CHART_OF_ACCOUNTS: DefaultAccountDefinition[] = [
  { code: '1000', name: 'Kassa', type: AccountType.ASSET, department: null, normalBalance: NormalBalance.DEBIT, systemKey: 'cash' },
  { code: '1010', name: 'Bank hisobvarag\'i', type: AccountType.ASSET, department: null, normalBalance: NormalBalance.DEBIT, systemKey: 'bank_transfer' },
  { code: '1020', name: 'Karta to\'lovlari kliringi', type: AccountType.ASSET, department: null, normalBalance: NormalBalance.DEBIT, systemKey: 'card_clearing' },
  { code: '1100', name: 'Mehmonlar hisobvarag\'i (Guest Ledger)', type: AccountType.ASSET, department: null, normalBalance: NormalBalance.DEBIT, systemKey: 'guest_ledger_ar' },
  { code: '1110', name: 'Boshqa debitorlik qarzlar', type: AccountType.ASSET, department: null, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '1200', name: 'Ombor zaxiralari', type: AccountType.ASSET, department: null, normalBalance: NormalBalance.DEBIT, systemKey: 'inventory' },
  { code: '1300', name: 'Oldindan to\'langan xarajatlar', type: AccountType.ASSET, department: null, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '1500', name: 'Asosiy vositalar', type: AccountType.ASSET, department: null, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '1510', name: 'Asosiy vositalar amortizatsiyasi (to\'plangan)', type: AccountType.ASSET, department: null, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '2000', name: 'Kreditorlik qarzlar (ta\'minotchilar)', type: AccountType.LIABILITY, department: null, normalBalance: NormalBalance.CREDIT, systemKey: 'accounts_payable' },
  { code: '2100', name: 'To\'lanishi kerak soliqlar', type: AccountType.LIABILITY, department: null, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '2110', name: 'QQS (VAT) majburiyati', type: AccountType.LIABILITY, department: null, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '2200', name: 'Mehmon depozitlari / oldindan to\'lovlar', type: AccountType.LIABILITY, department: null, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '2300', name: 'Xodimlarga to\'lanadigan ish haqi', type: AccountType.LIABILITY, department: null, normalBalance: NormalBalance.CREDIT, systemKey: 'payroll_liability' },
  { code: '2900', name: 'Uzoq muddatli qarzlar', type: AccountType.LIABILITY, department: null, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '3000', name: 'Ustav kapitali', type: AccountType.EQUITY, department: null, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '3900', name: 'Taqsimlanmagan foyda', type: AccountType.EQUITY, department: null, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4100', name: 'Transient — Retail', type: AccountType.REVENUE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4101', name: 'Transient — Discount', type: AccountType.REVENUE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4102', name: 'Transient — Negotiated', type: AccountType.REVENUE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4103', name: 'Transient — Qualified', type: AccountType.REVENUE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4104', name: 'Transient — Wholesale', type: AccountType.REVENUE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4110', name: 'Group — Corporate', type: AccountType.REVENUE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4111', name: 'Group — Association/Convention', type: AccountType.REVENUE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4112', name: 'Group — Government', type: AccountType.REVENUE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4113', name: 'Group — Tour/Wholesalers', type: AccountType.REVENUE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4114', name: 'Group — SMERF', type: AccountType.REVENUE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4120', name: 'Contract Rooms Revenue', type: AccountType.REVENUE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4130', name: 'Other Rooms Revenue', type: AccountType.REVENUE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.CREDIT, systemKey: 'room_revenue' },
  { code: '4190', name: 'Less: Allowances (Rooms)', type: AccountType.REVENUE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5100', name: 'Compensation — Front Office', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5101', name: 'Compensation — Guest Services', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5102', name: 'Compensation — Housekeeping', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5103', name: 'Compensation — Laundry', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5104', name: 'Compensation — Reservations', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5105', name: 'Compensation — Transportation', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5106', name: 'Compensation — Management', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5107', name: 'Service Charge Distribution', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5108', name: 'Contracted, Leased & Outsourced Labor', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5109', name: 'Bonuses & Incentives', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5110', name: 'Payroll-Related Expenses', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5140', name: 'Cleaning Supplies', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5141', name: 'Cluster Services', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5142', name: 'Commissions', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5143', name: 'Commissions and Fees — Group', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5144', name: 'Complimentary Food and Beverage', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5145', name: 'Complimentary Services and Gifts', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5146', name: 'Contract Services', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5147', name: 'Corporate-Office Reimbursables', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5148', name: 'Decorations', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5149', name: 'Dues and Subscriptions', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5150', name: 'Entertainment — In-House', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5151', name: 'Equipment Rental', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5152', name: 'Guest Relocation', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5153', name: 'Guest Supplies', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5154', name: 'Guest Transportation', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5155', name: 'Laundry and Dry Cleaning', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5156', name: 'Licenses and Permits', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5157', name: 'Linen', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5158', name: 'Loyalty Program Member Benefits', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5159', name: 'Miscellaneous', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5160', name: 'Postage and Overnight Delivery Charges', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5161', name: 'Printing and Stationery', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5162', name: 'Reservations', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5163', name: 'Training', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5164', name: 'Travel — Meals and Entertainment', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5165', name: 'Travel — Other', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5166', name: 'Uniforms', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5167', name: 'Uniform Laundry', type: AccountType.EXPENSE, department: AccountDepartment.ROOMS, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '4200', name: 'Food — Venue', type: AccountType.REVENUE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4201', name: 'Food — In-Room Dining', type: AccountType.REVENUE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4202', name: 'Food — Banquet/Conference/Catering', type: AccountType.REVENUE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4203', name: 'Food — Other', type: AccountType.REVENUE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.CREDIT, systemKey: 'fb_revenue' },
  { code: '4210', name: 'Beverage — Venue', type: AccountType.REVENUE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4211', name: 'Beverage — In-Room Dining', type: AccountType.REVENUE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4212', name: 'Beverage — Banquet/Conference/Catering', type: AccountType.REVENUE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4213', name: 'Beverage — Other', type: AccountType.REVENUE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4220', name: 'Audiovisual Revenue', type: AccountType.REVENUE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4221', name: 'Function Room Rentals and Setup Charges', type: AccountType.REVENUE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4222', name: 'Surcharges and Service Charges', type: AccountType.REVENUE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4223', name: 'Miscellaneous Other Revenue', type: AccountType.REVENUE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4290', name: 'Less: Allowances (F&B)', type: AccountType.REVENUE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5200', name: 'Cost of Food', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: 'cogs_fb' },
  { code: '5201', name: 'Cost of Beverage', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5202', name: 'Cost of Other Revenue — Audiovisual', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5203', name: 'Cost of Other Revenue — Miscellaneous', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5210', name: 'Compensation — Service', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5211', name: 'Compensation — Kitchen', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5212', name: 'Compensation — Banquet/Conference/Catering Service', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5213', name: 'Compensation — In-Room Dining', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5214', name: 'Compensation — Venues', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5215', name: 'Compensation — Management', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5216', name: 'Service Charge Distribution', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5217', name: 'Contracted, Leased & Outsourced Labor', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5218', name: 'Bonuses & Incentives', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5219', name: 'Payroll-Related Expenses', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5240', name: 'Banquet', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5241', name: 'China', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5242', name: 'Cleaning Supplies', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5243', name: 'Cluster Services', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5244', name: 'Commissions', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5245', name: 'Complimentary Services and Gifts', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5246', name: 'Contract Services', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5247', name: 'Corporate-Office Reimbursables', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5248', name: 'Decorations', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5249', name: 'Dishwashing Supplies', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5250', name: 'Dues and Subscriptions', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5251', name: 'Entertainment — In-House', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5252', name: 'Equipment Rental', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5253', name: 'Flatware', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5254', name: 'Glassware', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5255', name: 'Ice', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5256', name: 'Kitchen Fuel', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5257', name: 'Kitchen Smallwares', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5258', name: 'Laundry and Dry Cleaning', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5259', name: 'Licenses and Permits', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5260', name: 'Linen', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5261', name: 'Management Fees', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5262', name: 'Menus and Beverage Lists', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5263', name: 'Miscellaneous', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5264', name: 'Music and Entertainment', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5265', name: 'Operating Supplies', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5266', name: 'Paper and Plastics', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5267', name: 'Postage and Overnight Delivery Charges', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5268', name: 'Printing and Stationery', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5269', name: 'Reservations', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5270', name: 'Royalty Fees', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5271', name: 'Training', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5272', name: 'Travel — Meals and Entertainment', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5273', name: 'Travel — Other', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5274', name: 'Uniforms', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5275', name: 'Uniform Laundry', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '5276', name: 'Utensils', type: AccountType.EXPENSE, department: AccountDepartment.FOOD_BEVERAGE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '4300', name: 'Other Operated Revenue', type: AccountType.REVENUE, department: AccountDepartment.OTHER_OPERATED, normalBalance: NormalBalance.CREDIT, systemKey: 'other_operated_revenue' },
  { code: '5300', name: 'Other Operated Expense', type: AccountType.EXPENSE, department: AccountDepartment.OTHER_OPERATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '4900', name: 'Attrition Fees', type: AccountType.REVENUE, department: AccountDepartment.MISCELLANEOUS_INCOME, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4901', name: 'Cancellation Fees', type: AccountType.REVENUE, department: AccountDepartment.MISCELLANEOUS_INCOME, normalBalance: NormalBalance.CREDIT, systemKey: 'cancellation_fee_revenue' },
  { code: '4902', name: 'Cash Discounts Earned', type: AccountType.REVENUE, department: AccountDepartment.MISCELLANEOUS_INCOME, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4903', name: 'Commissions', type: AccountType.REVENUE, department: AccountDepartment.MISCELLANEOUS_INCOME, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4904', name: 'Destination/Resort/Urban Fees', type: AccountType.REVENUE, department: AccountDepartment.MISCELLANEOUS_INCOME, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4905', name: 'Extraordinary Cleaning Fees', type: AccountType.REVENUE, department: AccountDepartment.MISCELLANEOUS_INCOME, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4906', name: 'Guest-Related FX Gains (Losses)', type: AccountType.REVENUE, department: AccountDepartment.MISCELLANEOUS_INCOME, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4907', name: 'Guest Laundry and Dry Cleaning', type: AccountType.REVENUE, department: AccountDepartment.MISCELLANEOUS_INCOME, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4908', name: 'Interest Income', type: AccountType.REVENUE, department: AccountDepartment.MISCELLANEOUS_INCOME, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4909', name: 'Net Revenue from Renting Mixed-Ownership Units', type: AccountType.REVENUE, department: AccountDepartment.MISCELLANEOUS_INCOME, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4910', name: 'Other Breakage', type: AccountType.REVENUE, department: AccountDepartment.MISCELLANEOUS_INCOME, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4911', name: 'Proceeds from Business Interruption Insurance', type: AccountType.REVENUE, department: AccountDepartment.MISCELLANEOUS_INCOME, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4912', name: 'Space Rental and Concessions', type: AccountType.REVENUE, department: AccountDepartment.MISCELLANEOUS_INCOME, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '4990', name: 'Less: Promotional Credits', type: AccountType.REVENUE, department: AccountDepartment.MISCELLANEOUS_INCOME, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6100', name: 'Compensation — Accounting', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6101', name: 'Compensation — General Support', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6102', name: 'Compensation — Human Resources', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6103', name: 'Compensation — Purchasing/Receiving', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6104', name: 'Compensation — Security', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6105', name: 'Compensation — Management', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6106', name: 'Service Charge Distribution', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6107', name: 'Contracted, Leased & Outsourced Labor', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6108', name: 'Bonuses & Incentives', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6109', name: 'Payroll-Related Expenses', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: 'payroll_expense' },
  { code: '6130', name: 'Audit Charges', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6131', name: 'Bank Charges', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6132', name: 'Cash Overages and Shortages', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6133', name: 'Centralized Accounting Charges', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6134', name: 'Cluster Services', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6135', name: 'Complimentary Services and Gifts', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6136', name: 'Contract Services', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6137', name: 'Corporate-Office Reimbursables', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6138', name: 'Credit and Collection', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6139', name: 'Credit-Card Commissions', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6140', name: 'Decorations', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6141', name: 'Donations', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6142', name: 'Dues and Subscriptions', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6143', name: 'Entertainment — In-House', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6144', name: 'Equipment Rental', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6145', name: 'Human Resources — Recruitment/Relocation', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6146', name: 'Human Resources — Employee Relations', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6147', name: 'Legal Services', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6148', name: 'Licenses and Permits', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6149', name: 'Loss and Damages', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: 'inventory_variance' },
  { code: '6150', name: 'Miscellaneous', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6151', name: 'Nonguest-Related FX Gains (Losses)', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6152', name: 'Operating Supplies', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6153', name: 'Payroll Processing', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6154', name: 'Postage and Overnight Delivery Charges', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6155', name: 'Professional Fees', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6156', name: 'Provision for Doubtful Accounts', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6157', name: 'Security', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6158', name: 'Service Recovery', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6159', name: 'Settlement', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6160', name: 'Staff Transportation', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6161', name: 'Training', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6162', name: 'Travel — Meals and Entertainment', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6163', name: 'Travel — Other', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6164', name: 'Uniforms', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6165', name: 'Uniform Laundry', type: AccountType.EXPENSE, department: AccountDepartment.ADMIN_GENERAL, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6200', name: 'Compensation — Information Technology', type: AccountType.EXPENSE, department: AccountDepartment.INFO_TELECOM, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6201', name: 'Compensation — Telecommunications', type: AccountType.EXPENSE, department: AccountDepartment.INFO_TELECOM, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6202', name: 'Compensation — Management', type: AccountType.EXPENSE, department: AccountDepartment.INFO_TELECOM, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6203', name: 'Service Charge Distribution', type: AccountType.EXPENSE, department: AccountDepartment.INFO_TELECOM, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6204', name: 'Contracted, Leased & Outsourced Labor', type: AccountType.EXPENSE, department: AccountDepartment.INFO_TELECOM, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6205', name: 'Bonuses & Incentives', type: AccountType.EXPENSE, department: AccountDepartment.INFO_TELECOM, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6206', name: 'Payroll-Related Expenses', type: AccountType.EXPENSE, department: AccountDepartment.INFO_TELECOM, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6220', name: 'Cost of Cell Phones', type: AccountType.EXPENSE, department: AccountDepartment.INFO_TELECOM, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6221', name: 'Cost of Complimentary In-Room/Media Entertainment', type: AccountType.EXPENSE, department: AccountDepartment.INFO_TELECOM, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6222', name: 'Cost of Internet Services', type: AccountType.EXPENSE, department: AccountDepartment.INFO_TELECOM, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6223', name: 'Cost of Local Calls', type: AccountType.EXPENSE, department: AccountDepartment.INFO_TELECOM, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6224', name: 'Cost of Long-Distance Calls', type: AccountType.EXPENSE, department: AccountDepartment.INFO_TELECOM, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6225', name: 'Other Cost of Services', type: AccountType.EXPENSE, department: AccountDepartment.INFO_TELECOM, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6230', name: 'System Expenses (barcha tizimlar)', type: AccountType.EXPENSE, department: AccountDepartment.INFO_TELECOM, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6240', name: 'Cluster Services', type: AccountType.EXPENSE, department: AccountDepartment.INFO_TELECOM, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6241', name: 'Contract Services', type: AccountType.EXPENSE, department: AccountDepartment.INFO_TELECOM, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6242', name: 'Corporate-Office Reimbursables', type: AccountType.EXPENSE, department: AccountDepartment.INFO_TELECOM, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6243', name: 'Dues and Subscriptions', type: AccountType.EXPENSE, department: AccountDepartment.INFO_TELECOM, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6244', name: 'Entertainment — In-House', type: AccountType.EXPENSE, department: AccountDepartment.INFO_TELECOM, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6245', name: 'Equipment Rental', type: AccountType.EXPENSE, department: AccountDepartment.INFO_TELECOM, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6246', name: 'Miscellaneous', type: AccountType.EXPENSE, department: AccountDepartment.INFO_TELECOM, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6247', name: 'Operating Supplies', type: AccountType.EXPENSE, department: AccountDepartment.INFO_TELECOM, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6248', name: 'Other Equipment', type: AccountType.EXPENSE, department: AccountDepartment.INFO_TELECOM, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6249', name: 'System Storage and Optimization', type: AccountType.EXPENSE, department: AccountDepartment.INFO_TELECOM, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6250', name: 'Training', type: AccountType.EXPENSE, department: AccountDepartment.INFO_TELECOM, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6251', name: 'Travel — Meals and Entertainment', type: AccountType.EXPENSE, department: AccountDepartment.INFO_TELECOM, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6252', name: 'Travel — Other', type: AccountType.EXPENSE, department: AccountDepartment.INFO_TELECOM, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6253', name: 'Uniforms', type: AccountType.EXPENSE, department: AccountDepartment.INFO_TELECOM, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6254', name: 'Uniform Laundry', type: AccountType.EXPENSE, department: AccountDepartment.INFO_TELECOM, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6300', name: 'Compensation — Sales', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6301', name: 'Compensation — Marketing', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6302', name: 'Compensation — Management', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6303', name: 'Service Charge Distribution', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6304', name: 'Contracted, Leased & Outsourced Labor', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6305', name: 'Bonuses & Incentives', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6306', name: 'Payroll-Related Expenses', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6320', name: 'Advertising — Print, Radio and TV', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6321', name: 'Cluster Services', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6322', name: 'Complimentary Services and Gifts', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6323', name: 'Contract Services', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6324', name: 'Corporate-Office Reimbursables', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6325', name: 'Decorations', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6326', name: 'Digital — Paid Search', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6327', name: 'Digital — Display', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6328', name: 'Digital — Social', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6329', name: 'Direct-Response Marketing', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6330', name: 'Dues and Subscriptions', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6331', name: 'Entertainment — In-House', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6332', name: 'Equipment Rental', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6333', name: 'Familiarization Trips', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6334', name: 'Franchise and Affiliation — Marketing', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6335', name: 'Franchise and Affiliation — Royalties', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6336', name: 'Graphic Design', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6337', name: 'Loyalty Programs', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6338', name: 'Loyalty Programs — Promotion', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6339', name: 'Marketing Agency Fees', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6340', name: 'Miscellaneous', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6341', name: 'Operating Supplies', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6342', name: 'Outside Sales Representation', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6343', name: 'Outside Services Market Research', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6344', name: 'Outside Signage', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6345', name: 'Photography and Videography', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6346', name: 'Postage and Overnight Delivery Charges', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6347', name: 'Printed Collateral', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6348', name: 'Promotion', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6349', name: 'Tradeshows', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6350', name: 'Training', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6351', name: 'Travel — Meals and Entertainment', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6352', name: 'Travel — Other', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6353', name: 'Uniform Laundry', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6354', name: 'Website', type: AccountType.EXPENSE, department: AccountDepartment.SALES_MARKETING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6400', name: 'Compensation', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6401', name: 'Service Charge Distribution', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6402', name: 'Contracted, Leased & Outsourced Labor', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6403', name: 'Bonuses & Incentives', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6404', name: 'Payroll-Related Expenses', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6410', name: 'Building', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6411', name: 'Cluster Services', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6412', name: 'Contract Services', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6413', name: 'Corporate-Office Reimbursables', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6414', name: 'Dues and Subscriptions', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6415', name: 'Electrical and Mechanical Equipment', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6416', name: 'Elevators and Escalators', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6417', name: 'Engineering Supplies', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6418', name: 'Entertainment — In-House', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6419', name: 'Equipment Rental', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6420', name: 'Floor Covering', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6421', name: 'Furniture and Equipment', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6422', name: 'Grounds Maintenance and Landscaping', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6423', name: 'Heating, Ventilation, and Air-Conditioning Equipment', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6424', name: 'Kitchen Equipment', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6425', name: 'Laundry Equipment', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6426', name: 'Licenses and Permits', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6427', name: 'Life Safety', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6428', name: 'Light Bulbs', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6429', name: 'Miscellaneous', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6430', name: 'Operating Supplies', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: 'general_supplies_expense' },
  { code: '6431', name: 'Painting and Wall Covering', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6432', name: 'Plumbing', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6433', name: 'Swimming Pool', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6434', name: 'Training', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6435', name: 'Travel — Meals and Entertainment', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6436', name: 'Travel — Other', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6437', name: 'Uniforms', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6438', name: 'Uniform Laundry', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6439', name: 'Vehicle Repair', type: AccountType.EXPENSE, department: AccountDepartment.PROPERTY_MAINTENANCE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6500', name: 'Electricity', type: AccountType.EXPENSE, department: AccountDepartment.ENERGY_WATER_WASTE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6501', name: 'Fuels, Gases, and District Energy', type: AccountType.EXPENSE, department: AccountDepartment.ENERGY_WATER_WASTE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6502', name: 'Renewable Energy', type: AccountType.EXPENSE, department: AccountDepartment.ENERGY_WATER_WASTE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6503', name: 'Vehicle Fuels', type: AccountType.EXPENSE, department: AccountDepartment.ENERGY_WATER_WASTE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6510', name: 'Municipal Water', type: AccountType.EXPENSE, department: AccountDepartment.ENERGY_WATER_WASTE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6511', name: 'Other Water', type: AccountType.EXPENSE, department: AccountDepartment.ENERGY_WATER_WASTE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6512', name: 'Sewer', type: AccountType.EXPENSE, department: AccountDepartment.ENERGY_WATER_WASTE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6520', name: 'Landfill or Incineration', type: AccountType.EXPENSE, department: AccountDepartment.ENERGY_WATER_WASTE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6521', name: 'Recycled Waste', type: AccountType.EXPENSE, department: AccountDepartment.ENERGY_WATER_WASTE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6522', name: 'Composted Waste', type: AccountType.EXPENSE, department: AccountDepartment.ENERGY_WATER_WASTE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6523', name: 'Other Diverted Waste', type: AccountType.EXPENSE, department: AccountDepartment.ENERGY_WATER_WASTE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6530', name: 'Contract Services (Energy/Water/Waste)', type: AccountType.EXPENSE, department: AccountDepartment.ENERGY_WATER_WASTE, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6600', name: 'Government-Mandated Payroll Taxes — Disability Insurance', type: AccountType.EXPENSE, department: AccountDepartment.PAYROLL_RELATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6601', name: 'Government-Mandated Payroll Taxes — Medical Insurance', type: AccountType.EXPENSE, department: AccountDepartment.PAYROLL_RELATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6602', name: 'Government-Mandated Payroll Taxes — Retirement Contribution', type: AccountType.EXPENSE, department: AccountDepartment.PAYROLL_RELATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6603', name: 'Government-Mandated Payroll Taxes — Unemployment Insurance', type: AccountType.EXPENSE, department: AccountDepartment.PAYROLL_RELATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6604', name: 'Government-Mandated Payroll Taxes — Other Payroll Taxes', type: AccountType.EXPENSE, department: AccountDepartment.PAYROLL_RELATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6610', name: 'Supplemental Pay — Holiday Pay', type: AccountType.EXPENSE, department: AccountDepartment.PAYROLL_RELATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6611', name: 'Supplemental Pay — Other Pay', type: AccountType.EXPENSE, department: AccountDepartment.PAYROLL_RELATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6612', name: 'Supplemental Pay — Parental Leave', type: AccountType.EXPENSE, department: AccountDepartment.PAYROLL_RELATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6613', name: 'Supplemental Pay — Personal Days', type: AccountType.EXPENSE, department: AccountDepartment.PAYROLL_RELATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6614', name: 'Supplemental Pay — Severance Pay', type: AccountType.EXPENSE, department: AccountDepartment.PAYROLL_RELATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6615', name: 'Supplemental Pay — Sick Pay', type: AccountType.EXPENSE, department: AccountDepartment.PAYROLL_RELATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6616', name: 'Supplemental Pay — Vacation or Paid Time Off', type: AccountType.EXPENSE, department: AccountDepartment.PAYROLL_RELATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6630', name: 'Employee Benefits — Automobile Allowance', type: AccountType.EXPENSE, department: AccountDepartment.PAYROLL_RELATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6631', name: 'Employee Benefits — Childcare', type: AccountType.EXPENSE, department: AccountDepartment.PAYROLL_RELATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6632', name: 'Employee Benefits — Contributory Savings Plan or Profit Sharing', type: AccountType.EXPENSE, department: AccountDepartment.PAYROLL_RELATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6633', name: 'Employee Benefits — Dental Insurance', type: AccountType.EXPENSE, department: AccountDepartment.PAYROLL_RELATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6634', name: 'Employee Benefits — Disability Insurance', type: AccountType.EXPENSE, department: AccountDepartment.PAYROLL_RELATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6635', name: 'Employee Benefits — Expatriate Benefits', type: AccountType.EXPENSE, department: AccountDepartment.PAYROLL_RELATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6636', name: 'Employee Benefits — Group Life Insurance', type: AccountType.EXPENSE, department: AccountDepartment.PAYROLL_RELATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6637', name: 'Employee Benefits — Health Insurance', type: AccountType.EXPENSE, department: AccountDepartment.PAYROLL_RELATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6638', name: 'Employee Benefits — Housing and Educational', type: AccountType.EXPENSE, department: AccountDepartment.PAYROLL_RELATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6639', name: 'Employee Benefits — Meals', type: AccountType.EXPENSE, department: AccountDepartment.PAYROLL_RELATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6640', name: 'Employee Benefits — Miscellaneous', type: AccountType.EXPENSE, department: AccountDepartment.PAYROLL_RELATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6641', name: 'Employee Benefits — Nonunion Insurance', type: AccountType.EXPENSE, department: AccountDepartment.PAYROLL_RELATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6642', name: 'Employee Benefits — Nonunion Pension', type: AccountType.EXPENSE, department: AccountDepartment.PAYROLL_RELATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6643', name: 'Employee Benefits — Public Subsidized Transportation', type: AccountType.EXPENSE, department: AccountDepartment.PAYROLL_RELATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6644', name: 'Employee Benefits — Union Insurance', type: AccountType.EXPENSE, department: AccountDepartment.PAYROLL_RELATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6645', name: 'Employee Benefits — Union Other', type: AccountType.EXPENSE, department: AccountDepartment.PAYROLL_RELATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6646', name: 'Employee Benefits — Union Pension', type: AccountType.EXPENSE, department: AccountDepartment.PAYROLL_RELATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '6647', name: 'Employee Benefits — Worker\'s Compensation Insurance', type: AccountType.EXPENSE, department: AccountDepartment.PAYROLL_RELATED, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '7000', name: 'Base Fee', type: AccountType.EXPENSE, department: AccountDepartment.MANAGEMENT_FEES, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '7001', name: 'Incentive Fees', type: AccountType.EXPENSE, department: AccountDepartment.MANAGEMENT_FEES, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '7100', name: 'Lease Income', type: AccountType.REVENUE, department: AccountDepartment.NONOPERATING, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '7101', name: 'Cost Recovery Income', type: AccountType.REVENUE, department: AccountDepartment.NONOPERATING, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '7102', name: 'Interest Income (Nonoperating)', type: AccountType.REVENUE, department: AccountDepartment.NONOPERATING, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '7103', name: 'Other Nonoperating Income', type: AccountType.REVENUE, department: AccountDepartment.NONOPERATING, normalBalance: NormalBalance.CREDIT, systemKey: null },
  { code: '7110', name: 'Rent — Land and Buildings', type: AccountType.EXPENSE, department: AccountDepartment.NONOPERATING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '7111', name: 'Rent — Other Property and Equipment', type: AccountType.EXPENSE, department: AccountDepartment.NONOPERATING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '7120', name: 'Business and Occupation Taxes', type: AccountType.EXPENSE, department: AccountDepartment.NONOPERATING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '7121', name: 'Other Taxes and Assessments', type: AccountType.EXPENSE, department: AccountDepartment.NONOPERATING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '7122', name: 'Personal Property Taxes', type: AccountType.EXPENSE, department: AccountDepartment.NONOPERATING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '7123', name: 'Real Estate Taxes', type: AccountType.EXPENSE, department: AccountDepartment.NONOPERATING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '7130', name: 'Insurance — Building and Contents', type: AccountType.EXPENSE, department: AccountDepartment.NONOPERATING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '7131', name: 'Insurance — Liability', type: AccountType.EXPENSE, department: AccountDepartment.NONOPERATING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '7132', name: 'Insurance — Deductible', type: AccountType.EXPENSE, department: AccountDepartment.NONOPERATING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '7140', name: 'Cost Recovery Expense', type: AccountType.EXPENSE, department: AccountDepartment.NONOPERATING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '7141', name: 'Gain or Loss on Fixed Assets', type: AccountType.EXPENSE, department: AccountDepartment.NONOPERATING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '7142', name: 'Owner Expense', type: AccountType.EXPENSE, department: AccountDepartment.NONOPERATING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '7143', name: 'Pre-opening Expense', type: AccountType.EXPENSE, department: AccountDepartment.NONOPERATING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '7144', name: 'Unrealized Investment Gains or Losses', type: AccountType.EXPENSE, department: AccountDepartment.NONOPERATING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '7145', name: 'Unrealized Foreign Exchange Gains or Losses', type: AccountType.EXPENSE, department: AccountDepartment.NONOPERATING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '7200', name: 'Interest Expense', type: AccountType.EXPENSE, department: AccountDepartment.NONOPERATING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '7201', name: 'Depreciation Expense', type: AccountType.EXPENSE, department: AccountDepartment.NONOPERATING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '7202', name: 'Amortization Expense', type: AccountType.EXPENSE, department: AccountDepartment.NONOPERATING, normalBalance: NormalBalance.DEBIT, systemKey: null },
  { code: '7300', name: 'Income Tax Expense', type: AccountType.EXPENSE, department: AccountDepartment.NONOPERATING, normalBalance: NormalBalance.DEBIT, systemKey: null },
];
